#!/usr/bin/env bash

set -e

mkdir -p ~/.ssh
echo $BITBUCKET_BASE64_SSH_KEY | base64 --decode > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa

echo "~/.ssh/id_rsa private key created from BITBUCKET_BASE64_SSH_KEY variable"