#!/usr/bin/env bash

set -e

mkdir -p ~/.ssh
chmod 700 ~/.ssh
if [ -z "$BITBUCKET_BASE64_SSH_KEY" ]; then
    echo "BITBUCKET_BASE64_SSH_KEY env variable is not set"
    exit 1
fi
echo $BITBUCKET_BASE64_SSH_KEY | base64 --decode > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa

echo "~/.ssh/id_rsa private key created from BITBUCKET_BASE64_SSH_KEY variable"